[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"
default-run = "advent_of_code"
publish = false


[lib]
doctest = false

[features]
test_lib = []


[dependencies]
colored = "2.0.4"
itertools = "0.12.0"
pico-args = "0.5"
